name: Manual production release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag
        required: true
        type: string

concurrency:
  group: ${{ inputs.tag }}

jobs:
  release:
    uses: digabi/workflows-common/.github/workflows/digabi2-companion-app-prod-release.yml@5815bd12026c83a2d361f867e3a9d9a32ac2e8eb
    with:
      app-name: klecks
      aws-access-role: KlecksGithubActionsAccessRole
      tag: ${{ inputs.tag }}
    secrets: inherit
